CHANGELOG.md, README.md, synedrion/src/cggmp21/protocols.rs, synedrion/src/cggmp21/protocols/generic.rs, synedrion/src/cggmp21/protocols/interactive_signing.rs, synedrion/src/cggmp21/protocols/key_gen.rs, synedrion/src/cggmp21/protocols/key_init.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/key_resharing.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/cggmp21/protocols/test_utils.rs, synedrion/src/cggmp21/protocols/threshold.rs, synedrion/src/cggmp21/protocols/wrappers.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/sessions/states.rs, synedrion/src/sessions/type_erased.rs, synedrion/src/tools/collections.rs, synedrion/src/tools/sss.rs, synedrion/tests/sessions.rs
A part of #20. Not closing it yet since I'm not certain it's the best protocol to use, and it needs to be properly integrated with the rest of the framework. Also there is one pathway where a possible error is not attributable to any party - can be avoided by assuming that each party has access to public parts of keyshares of other nodes.
Merging this now because it has grown pretty big. Still more work needed to close the mentioned issues. 
Public:
- Added a "key resharing" protocol based on T. M. Wong, C. Wang, J. M. Wing "Verifiable Secret Redistribution for Archive Systems"(https://www.cs.cmu.edu/~wing/publications/Wong-Winga02.pdf, https://doi.org/10.1109/SISW.2002.1183515). Specifically, REDIST protocol.
Internal:
- Switched from using `HoleVec` to `BTreeMap` when accumulating …
=> Implement a key resharing protocol

synedrion/src/cggmp21/params.rs, synedrion/src/cggmp21/protocols/interactive_signing.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/cggmp21/sigma.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/enc.rs, synedrion/src/cggmp21/sigma/fac.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/cggmp21/sigma/mul.rs, synedrion/src/cggmp21/sigma/mul_star.rs, synedrion/src/cggmp21/sigma/prm.rs, synedrion/src/cggmp21/sigma/sch.rs, synedrion/src/common.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/paillier/keys.rs, synedrion/src/paillier/params.rs, synedrion/src/paillier/ring_pedersen.rs, synedrion/src/threshold.rs, synedrion/src/tools/hashing.rs, synedrion/src/uint.rs, synedrion/src/uint/bounded.rs, synedrion/src/uint/signed.rs, synedrion/src/uint/traits.rs, synedrion/src/www02.rs
- Include challenges in all ZK proofs. While not strictly necessary, according to the authors of the paper, still adds a little more security and more debug info at the price of slightly larger message sizes. Also we were already doing it for some of the ZK proofs anyway.
- Adjust method visibility (don't use `pub(crate)` for the methods of a struct that's already `pub(crate)`)
- Bring some parameter names in sync with the paper
- Decouple curve scalars from big integers (fixes #63). Note that it adds some internal-use methods to `SchemeParams`; these should be hidden as a part of #74.
- TODO: add public values and commitments (if the ZK proof uses them) into the hash digest for challenge generation, as prescribed by Fig. 2
=> ZK proof cleanup

synedrion/benches/bench.rs, synedrion/src/cggmp21/benches.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/enc.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mul.rs, synedrion/src/cggmp21/sigma/mul_star.rs, synedrion/src/common.rs, synedrion/src/lib.rs, synedrion/src/paillier.rs, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/keys.rs, synedrion/src/tools/collections.rs, synedrion/src/uint/signed.rs
- Add `CiphertextMod` that includes the public key used to created it. Fixes #59 
- Add sanity checks in proof constructors - check that the scalar values are in the required range, and ciphertexts have consistent public keys. Fixes #64
Note that we could avoid passing the actual public keys in the proof constructors since they are already contained in ciphertexts. But:
- we already have them available, and it allows to catch some errors early;
- since the public key in the ciphertext is not hashed when creating the challenge, we need to add them to the hash explicitly, and it just makes it easier to eyeball the structure: the list of public inputs is exactly the list of method parameters, and is exactly the items passed to the hash.
=> Bundle public keys with Paillier ciphertexts

synedrion/src/cggmp21/params.rs, synedrion/src/cggmp21/protocols/key_init.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/cggmp21/sigma/mul_star.rs, synedrion/src/cggmp21/sigma/sch.rs, synedrion/src/common.rs, synedrion/src/curve.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/paillier/keys.rs, synedrion/src/threshold.rs, synedrion/src/tools/hashing.rs, synedrion/src/tools/sss.rs, synedrion/src/uint/bounded.rs, synedrion/src/uint/signed.rs, synedrion/src/www02.rs
- Add the missing range checks in aff-g, log*, and mul* proofs
- Add a check for the RSA modulus being a composite in the mod proof
- Add the missing primality check in the mod proof
- Hash in curve parameters and the number of parties in KeyInit and KeyRefresh; hash in curve parameters and share set IDs in Presigning and Signing  (updates #3, but not sure if closes it)
- Remove some unused curve arithmetic methods
- Optimize polynomial evaluation
=> Fixes for the audit week 1

synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/enc.rs, synedrion/src/cggmp21/sigma/fac.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/cggmp21/sigma/mul.rs, synedrion/src/cggmp21/sigma/mul_star.rs, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/ring_pedersen.rs, synedrion/src/uint/signed.rs, synedrion/src/uint/traits.rs
The paper requires this (see Fig. 2). Not doing that opens easy ways of forging valid-looking proofs. 
Also removing `Hashable` from `CiphertextMod` and `RPCommitmentMod` (and from `UintMod`), to make the retrievals explicit, in case we want to optimize them in future (perhaps some retrievals can be avoided). Keeping `Hashable` for `RPParamsMod`, but making it produce the same hash as the one for `RPParams`.
=> Add commitment to the hash when calculating non-interactive challenges

synedrion/src/cggmp21/params.rs
I was updating Entropy Core to use the latest Synedrion `HEAD` but got blocked because of
these missing trait implementations.
I only needed them for the Test and Production parameters, but figured adding them to the
Paillier parameters wouldn't hurt.
=> Implement `serde` for CGGMP21 params

.github/workflows/test.yml, synedrion/Cargo.toml, synedrion/src/cggmp21/protocols/aux_gen.rs, synedrion/src/cggmp21/protocols/key_gen.rs, synedrion/src/cggmp21/protocols/key_init.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/rounds/generic.rs, synedrion/src/rounds/test_utils.rs, synedrion/src/rounds/wrappers.rs, synedrion/src/sessions/session.rs, synedrion/src/sessions/type_erased.rs, synedrion/src/www02/key_resharing.rs, synedrion/tests/sessions.rs, synedrion/tests/threshold.rs
- Add a CI step to test building on the WASM target
- Add the RNG parameter to `Round::verify_message()`. Fixes #105
=> Fix WASM build

synedrion/src/lib.rs, synedrion/src/www02.rs, synedrion/src/www02/entities.rs, synedrion/tests/threshold.rs
I want to be able to use the derivation functionality from the on-chain Registry pallet
code, which doesn't have access to a `ThresholdKeyShare`. Instead it only has access to a
`VerifyingKey`.
This PR adds a new trait, `DeriveChildKey`, which is implemented for `ThresholdKeyShare`
and `VerifyingKey`, allowing both to derive child verification keys.
I also considered having just a standalone function, but figured it would be nice to
implement the method on both types. Let me know if you'd prefer the first solution.
I'm also not entirely sure how to test this. Given that the `ThresholdKeyShare` tests
already use the verifying key internally, it seems covered? But maybe at some point in
the future the implementations could differ and cause problems.
=> Make verification key derivation independent of keyshares

.github/workflows/cla.yaml
It is unlikely that users belonging to the `entropyxyz` GitHub Organization are required to sign the CLA. To automatically allow any Organization member to bypass the requirements to sign the CLA, merge this PR.
=> Add `entropyxyz` organization username to allowlist.

synedrion/Cargo.toml, synedrion/src/cggmp21/entities.rs, synedrion/src/cggmp21/protocols/aux_gen.rs, synedrion/src/cggmp21/protocols/key_init.rs, synedrion/src/cggmp21/protocols/key_refresh.rs, synedrion/src/cggmp21/protocols/presigning.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/paillier/keys.rs, synedrion/src/sessions/type_erased.rs, synedrion/src/www02/entities.rs, synedrion/src/www02/key_resharing.rs
I've been strugging to use Synedrion as a dependency in a Substrate pallet due to one of
its dependencies pulling in `std` transitively, as mentioned in https://github.com/entropyxyz/entropy-core/issues/961.
Through a bit of digging I found that the `bincode` and `secrecy` dependencies were
pulling in `serde` without disable default features, causing `std` to be pulled in.
I've updated them to the latest releases which use better feature management to allow
`serde` to not be pulled in with default features. Note that the latest releases are
technically pre-releases.
=> Bump `bincode` and `secrecy` for `no_std` builds

synedrion/src/cggmp21/protocols/signing.rs, synedrion/src/rounds/test_utils.rs
I noticed that the test for the signing protocol does not traverse the unhappy path, where signature verification fails and we generate a correctness proof for the verifying signer. So here's a test for that along some more testing utils.
=> Add a test for the unhappy path of signing

CHANGELOG.md, synedrion/Cargo.toml, synedrion/src/cggmp21/params.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/curve/ecdsa.rs, synedrion/src/uint.rs, synedrion/src/uint/traits.rs
This will make it possible for `entropy-core` to still use our `master` branch. `crypto-bigint` can stay at the pre-release since it is not directly exposed to the user.
=> Return all RustCrypto libs but `crypto-bigint` to stable versions

synedrion/Cargo.toml, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/keys.rs
- Bump `secrecy` to the most recent stable version (0.10) (this is an internal change)
- Bump `crypto-bigint` to 0.6-rc.6 and `crypto-primes` to 0.6.0-pre.2 (this is an internal change)
- Remove unused `base64` dependency and move `hex` to dev-dependencies (should have been done in #153)
- Remove the need for `getrandom/js` dependency (`crypto-primes`'s default features were requiring it, but we don't need those features)
- Remove an explicit `Debug` for `SecretKeyPaillier` - derivation works well enough
- Remove unncecessary `Zeroize` and `ZeroizeOnDrop` derivations (don't need `Zeroize` if `ZeroizeOnDrop` is already derived, and don't need `ZeroizeOnDrop` in structs that already have all secret data in `SecretBox`)
=> Assorted fixes

synedrion/src/cggmp21/aux_gen.rs, synedrion/src/cggmp21/entities.rs, synedrion/src/cggmp21/interactive_signing.rs, synedrion/src/cggmp21/key_refresh.rs, synedrion/src/cggmp21/params.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/enc.rs, synedrion/src/cggmp21/sigma/fac.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/cggmp21/sigma/mul.rs, synedrion/src/cggmp21/sigma/mul_star.rs, synedrion/src/cggmp21/sigma/prm.rs, synedrion/src/paillier.rs, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/keys.rs, synedrion/src/paillier/params.rs, synedrion/src/paillier/ring_pedersen.rs, synedrion/src/paillier/rsa.rs, synedrion/src/tools.rs, synedrion/src/tools/hide_debug.rs, synedrion/src/tools/secret.rs, synedrion/src/uint/bounded.rs, synedrion/src/uint/signed.rs, synedrion/src/uint/traits.rs
Part of #157
- Split Paillier keys and ring-Pedersen secrets, with the underlying `SecretPrimes`/`PublicModulus`. Note that according to the new version of the paper Paillier only needs `mod 3 = 4` primes, while ring-Pedersen needs safe primes.
- Use `Exponentiable` where approriate
- Normalize naming for "wire" and "expanded" structures in `paillier`. Namely: the wire ones have the "Wire" postfix, the expanded ones have no postfixes. The conversion methods are `to_wire()` and `to_precomputed()`.
- Changed the type of various Uint bit size arguments to `u32` to match `crypto-bigint`
The new `Secret` will be properly used throughout the codebase in a follow-up PR, this one is getting pretty big already.
=> Updates for CGGMP'24: Paillier/ring-Pedersen level 

synedrion/src/cggmp21/params.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/curve/ecdsa.rs
The concrete curve implementation we use (`k256`) assumes big endian byte order for scalars and field elements. The traits implemented are byte order agnostic. This PR makes the big-endian byte order explicit in naming and docs. And adds a test to prove that the order matters.
=> Be explicit about byte order expectations

Cargo.lock, synedrion/Cargo.toml
I find myself adding `tracing` and the `test_log` crate over and over while investigating things. I think it's useful enough that we should just go ahead and add them both. Thoughts?
=> Add tracing and test_log

synedrion/src/cggmp21/interactive_signing.rs, synedrion/src/cggmp21/sigma.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/enc.rs, synedrion/src/cggmp21/sigma/log_star.rs, synedrion/src/cggmp21/sigma/mul.rs, synedrion/src/cggmp21/sigma/mul_star.rs
Stacked on top of #166 
Group secret and public inputs into structs to make it more transparent which variables are substituted at the points of their use (since the variable names in the protocols don't always correspond to the variable names in the proofs)
=> Argument grouping for ZK proofs

synedrion/src/cggmp21/sigma/prm.rs
Removes the `PublicSigned` wrapper from the `proof` member of `PrmProof`. When using production-sized parameters, the totient is often a 2048 bit number and so doesn't fit in a signed number type.
The Prm proof components are all positive and reduced modulo the totient, hence guaranteed to fit in a totient-sized number type (i.e. 2048 bits), so wrapping them is unnessecary.
Fixes #174.
=> Don't use a PublicSigned for PrmProof

synedrion/src/cggmp21/aux_gen.rs, synedrion/src/cggmp21/aux_gen_tests.rs, synedrion/src/cggmp21/interactive_signing.rs, synedrion/src/cggmp21/key_init.rs, synedrion/src/cggmp21/key_refresh.rs, synedrion/src/cggmp21/key_refresh_tests.rs, synedrion/src/cggmp21/params.rs, synedrion/src/tools/hashing.rs
Switch to using the `XofHasher` and delete the `FofHasher` and, thus, the `HashOutput` associated type on `SchemeParams`. Instead of a fixed-length array we use `Box<[u8]>`.
Given these hashes are used for the Fiat-Shamir transform we need to ensure our hashes are not subject to bias. For this reason we read 2 * curve field size number of bytes from the hash.
=> Remove HashOutput from SchemeParams and delete FofHasher

synedrion/src/cggmp21/params.rs, synedrion/src/curve/arithmetic.rs, synedrion/src/curve/bip32.rs, synedrion/src/uint.rs, synedrion/src/uint/traits.rs
A replacement PR for https://github.com/entropyxyz/synedrion/pull/193 that requires some careful thought.
This PR uses `TinyCurve32` just like #193 but sets `PRIME_BITS` to the (wrong) value of 127, which avoids the test failures but is still about as correct as the previous TestParams.
=> Use TinyCurve32 for tests

synedrion/src/cggmp21/conversion.rs, synedrion/src/cggmp21/params.rs, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/keys.rs, synedrion/src/paillier/params.rs, synedrion/src/paillier/rsa.rs, synedrion/src/uint/secret_signed.rs
Setting the two MSBs when searching for RSA primes means they will have the bit length of a `P::Uint` which in turns means we do not need to explicitly provide modulus bounds. 
Builds on #195. Fixes #183.
=> RSA primes set the two MSBs

synedrion/src/cggmp21/interactive_signing_tests.rs
When using `nextest` to run tests, this PR cuts total running time from 8 to 4 sec, by splitting up the slowest tests into smaller units such that nextest's "test-per-process" model can execute them concurrently.
=> "ungroup" slow tests into individual tests for faster execution

PAPER.md, synedrion/src/cggmp21/conversion.rs, synedrion/src/cggmp21/entities.rs, synedrion/src/cggmp21/interactive_signing.rs, synedrion/src/cggmp21/params.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/paillier/encryption.rs, synedrion/src/paillier/keys.rs, synedrion/src/paillier/params.rs, synedrion/src/private_benches.rs, synedrion/src/uint/secret_signed.rs, synedrion/src/uint/secret_unsigned.rs
- Change the modulus size in `TestParams` to 128. 
- Ensure the correct size of `y` argument for `П^{dec}` (`delta_i` and `chi_i`). See the change in `PAPER.md` for the theoretical background. Most of the changes are just dealing with the `П^{dec}` now requiring some operations on wide Uints.
I think this is the correct approach from the mathematical perspective (although having to add some `_wide` methods is not great, see also #198). Fixes #187. I think it is safe to do since we added the `DEVIATION` comments in the proof itself, and the node in `PAPER.md`, so the future audit will review it.
=> Ensure correct size of `y` argument for `П^{dec}`

Cargo.lock, synedrion/Cargo.toml, synedrion/benches/zk_proofs.rs, synedrion/src/cggmp21.rs, synedrion/src/cggmp21/sigma/aff_g.rs, synedrion/src/cggmp21/sigma/aff_g_star.rs, synedrion/src/cggmp21/sigma/dec.rs, synedrion/src/cggmp21/sigma/elog.rs, synedrion/src/cggmp21/sigma/enc_elg.rs, synedrion/src/cggmp21/sigma/fac.rs, synedrion/src/cggmp21/sigma/mod_.rs, synedrion/src/cggmp21/sigma/prm.rs, synedrion/src/cggmp21/sigma/sch.rs, synedrion/src/lib.rs, synedrion/src/private_benches.rs
Flatten out the code and reduce repetitions in ZK proof benches, and also keep the `criterion` dependency in `dev-dependencies` only. Using the `iter_custom()` approach for now since `iter_batched()` requires either returning closures, or introducing additional structures holding prepared parameters for each ZK proof which seems more complicated. 
Note: I pre-calculate two Paillier keys and two RP params and save them in a `LazyLock` (since that's generally the slowest part of the setup). This means that tests lose a bit of variation, but I don't expect much variation on the Paillier key, since that would mean timing attacks are possible.
It would be nice to somehow merge the code in these benchmarks with the test code in ZK proof modules, but that is left for a follow-up PR.
=> Simplify ZK proof benches

Cargo.lock, Cargo.toml, src/entities/full.rs, src/entities/threshold.rs, src/protocols/aux_gen.rs, src/protocols/interactive_signing.rs, src/protocols/key_refresh.rs, src/protocols/key_resharing.rs
Fixes #185
Had to bump `tiny-curve` because in 0.2.0 activating `serde` feature did not actually make `VerifyingKey<TinyCurve>` serde-serializable; in 0.2.2 it does.
=> Use `SerializableMap` in serializable objects

CHANGELOG.md, Cargo.toml, src/curve.rs, src/curve/arithmetic.rs, src/entities.rs, src/entities/internal.rs, src/paillier.rs, src/paillier/params.rs, src/params.rs, src/params/dev.rs, src/params/k256.rs, src/params/traits.rs, src/protocols/aux_gen.rs, src/protocols/interactive_signing.rs, src/protocols/key_init.rs, src/protocols/key_refresh.rs, src/protocols/misbehavior_tests/aux_gen.rs, src/protocols/misbehavior_tests/key_refresh.rs, src/tools/hashing.rs, src/zk/aff_g.rs, src/zk/aff_g_star.rs, src/zk/dec.rs, src/zk/elog.rs, src/zk/enc_elg.rs, src/zk/fac.rs, src/zk/mod_.rs, src/zk/prm.rs, src/zk/sch.rs
- Make the hasher an associated type of `SchemeParams::Digest`, since we want the hash security to match overall security.
- Renamed `XofHasher` to `Hasher`.
- Wrapped hash output, SID, and EPID into their own types
- Hashing all scheme parameters, not just the curve order
=> Generic hash

src/entities/threshold.rs, src/protocols/key_resharing.rs, src/tools/sss.rs
I think it's more efficient to leverage BTreeMaps unique keys and avoid building BTreeSets when evaluating interpolation coefficients.
=> Save some clones while interpolating polynomial coefficients

CHANGELOG.md, Cargo.lock, Cargo.toml, src/curve/arithmetic.rs, src/lib.rs, src/paillier.rs, src/paillier/encryption.rs, src/paillier/keys.rs, src/paillier/params.rs, src/paillier/ring_pedersen.rs, src/paillier/rsa.rs, src/params/conversion.rs, src/params/dev.rs, src/params/k256.rs, src/params/traits.rs, src/tools/secret.rs, src/uint.rs, src/uint/public_signed.rs, src/uint/public_uint.rs, src/uint/secret_signed.rs, src/uint/secret_unsigned.rs, src/uint/traits.rs, src/zk/fac.rs, src/zk/mod_.rs, src/zk/prm.rs
- Disbanded `HasWide` into `Extendable` and `MulWide` with blanket implementations. This means that users would be able to implement their own `SchemeParams`, no longer restricted by the orphan rule.
- Replaced `Encoding` with `BoxedEncoding`, blanket-derived for all `Uint`s (and potentially derived for `BoxedUint`)
- Moved `ExtraWideUint` to `SchemeParams`
- Made `ExtraWideUint` smaller since it doesn't have to be double `WideUint` anymore
- Added consistency check for `PaillierParams`
- Made consistency checks compile-time assertions (**question:** is this a good idea? Perhaps we should instead have a method that would be able to return a error saying which specific condition was violated?)
- Added 128-bit security parameters for `k256`. Fixes #189. Note that the `ExtraWideUint` needs …
=> Disband `HasWide` and make it easier to define custom `SchemeParams`

.github/workflows/release-plz.yaml
This adds the release-plz CI using their [basic, recommended workflow yaml](https://release-plz.dev/docs/github/quickstart#3-setup-the-workflow) as a solution to https://github.com/entropyxyz/devops-infrastructure/issues/133.
I would like to iterate on this by creating a release-plz bot app and use that for our github token in the CI (see the [documented recommendation](https://release-plz.dev/docs/github/token#use-a-github-app)), but I don't think this is necessary for this first version and can follow up with a future PR.
=> Add release-plz workflow

Cargo.lock, Cargo.toml, src/entities/full.rs, src/entities/threshold.rs, src/paillier/keys.rs, src/paillier/ring_pedersen.rs, src/protocols/aux_gen.rs, src/protocols/interactive_signing.rs, src/protocols/key_init.rs, src/protocols/key_refresh.rs, src/protocols/key_resharing.rs, src/tools/sss.rs, src/zk/aff_g.rs, src/zk/aff_g_star.rs, src/zk/dec.rs, src/zk/elog.rs, src/zk/enc_elg.rs, src/zk/mod_.rs, src/zk/prm.rs, src/zk/sch.rs
Fixes #10
Also pin the trunk version of `manul` since it requires some fixes to work around a bug in `derive-where` (see https://github.com/ModProg/derive-where/pull/122)
=> Use `derive-where` instead of explicit bounds to derive `serde` traits
